project:
  type: website
  output-dir: docs

website:
  title: "ID529: Data Management and Analytic Workflows in R"
  favicon: "/assets/logo.svg"
  navbar:
    left:
      - text: Home 
        href: index.qmd
        icon: house
      - href: about.qmd
        icon: file-richtext
      - text: Curriculum
        icon: mortarboard
        menu:
        - text: Day 1
          href: day1.qmd
        - text: Day 2
          href: day2.qmd
        - text: Day 3
          href: day3.qmd
        - text: Day 4
          href: day4.qmd
        - text: Day 5
          href: day5.qmd
        - text: Day 6
          href: day6.qmd
        - text: Day 7
          href: day7.qmd
        - text: Day 8
          href: day8.qmd
        - text: Day 9
          href: day9.qmd
      - text: Past Years' Content
        icon: mortarboard
        menu: 
        - text: "2023"
          href: 2023.qmd
        - text: "2024"
          href: 2024.qmd
        - text: "2025"
          href: 2025.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
